name: Fetch SS Data and Push

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'  # 每2小时运行一次

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Show current time
        run: date

      - name: Run fetch_ss_data.py
        run: python fetch_ss_data.py

      - name: Check and show ss.txt
        run: |
          echo "== File content =="
          cat ss.txt || echo "ss.txt not found!"

      - name: Commit and push ss.txt to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ss.txt
          git diff --cached --quiet && echo "No changes detected, skipping commit." || (
            git commit -m "update ss.txt"
            git push origin main
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
